name = "BinanceHistoricalData"
uuid = "65988f70-63b6-46a1-ae72-5da8f3c99bd9"
authors = ["Philippe Casgrain <31874380+p-casgrain@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
